name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *' # Runs daily at 16:00 UTC

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rmq-version: ['v3.13.7', 'v4.2.x', 'main']
        include:
          - rmq-version: 'main'
            otp-version: 28
          - rmq-version: 'v4.2.x'
            otp-version: 27
          - rmq-version: 'v3.13.7'
            otp-version: 26
    steps:
      - id: restore-rabbitmq-server-cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ github.workspace }}/rabbitmq-server
          key: ${{ runner.os }}-v0-rabbitmq-server-${{ matrix.rmq-version }}
      - id: maybe-fail-rabbitmq-server-miss
        if: steps.restore-rabbitmq-server-cache.outputs.cache-hit != 'true'
        uses: actions/github-script@v8
        with:
          script: |
            core.setFailed('could not restore cached rabbitmq-server build');
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp-version }}
          elixir-version: '1.18'
      - uses: actions/checkout@v5
        with:
          path: rabbitmq-server/deps/aws
      - run: |
          make -C ${{ github.workspace }}/rabbitmq-server/deps/aws
      - run: |
          make -C ${{ github.workspace }}/rabbitmq-server/deps/aws tests
